param(
    [string]$GlfwVersion = "3.3.8",
    [string]$GlfwPlatformVersion = "3.4",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot "native\xbox-glfw\glfw_constants_generated.h"
}

function Get-GlfwHeader {
    param([string]$Version)
    $url = "https://raw.githubusercontent.com/glfw/glfw/$Version/include/GLFW/glfw3.h"
    Write-Host "Fetching $url"
    return (Invoke-WebRequest -Uri $url -UseBasicParsing).Content -split "`n"
}

function Get-DefineLines {
    param([string[]]$Lines)
    $defines = New-Object System.Collections.Generic.List[string]
    foreach ($line in $Lines) {
        $trimmed = $line.Trim()
        if ($trimmed -notmatch '^#define\s+GLFW_') { continue }
        if ($trimmed -match '/\*') { $trimmed = ($trimmed -split '/\*', 2)[0].TrimEnd() }
        if ($trimmed -match '\(') { continue }
        [void]$defines.Add($trimmed)
    }
    return $defines
}

$defines338 = Get-DefineLines -Lines (Get-GlfwHeader -Version $GlfwVersion)
$defines34 = Get-DefineLines -Lines (Get-GlfwHeader -Version $GlfwPlatformVersion) | Where-Object {
    $_ -match '^#define\s+GLFW_(ANY_PLATFORM|PLATFORM_WIN32|PLATFORM_COCOA|PLATFORM_WAYLAND|PLATFORM_X11|PLATFORM_NULL|PLATFORM_UNAVAILABLE|PLATFORM)\s'
}

$seen = @{}
$merged = New-Object System.Collections.Generic.List[string]
foreach ($def in ($defines338 + $defines34)) {
    if ($def -match '^#define\s+(GLFW_\w+)') {
        $name = $Matches[1]
        if (-not $seen.ContainsKey($name)) {
            $seen[$name] = $true
            [void]$merged.Add($def)
        }
    }
}

$header = @"
// AUTO-GENERATED by scripts/Generate-GlfwConstants.ps1 - do not edit by hand.
// GLFW $GlfwVersion constants from https://github.com/glfw/glfw (include/GLFW/glfw3.h)
// GLFW $GlfwPlatformVersion platform constants from the same upstream header (3.4+ API surface).
// Regenerate: .\scripts\Generate-GlfwConstants.ps1

#pragma once

"@

foreach ($def in $merged) { $header += "$def`n" }
$header += @"

#ifndef GLFW_VK_ERR_INIT_FAILED
#define GLFW_VK_ERR_INIT_FAILED (-3)
#endif

"@

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null
[System.IO.File]::WriteAllText($OutputPath, $header.TrimEnd() + "`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($merged.Count) defines to $OutputPath"
